### ISSUE TITLE
Date of data uploaded

### ISSUE THREAD

**Issue by valitsa** [valitsa/ESPmapping#1]
For each record in the database keep track of when data was uploaded or when the last edit was made. Make this also visible in the data view

**Comment by brtvrbvk** [comment]
what do you mean by record? study? Indicator?,...
visible in dataview: title of the collumn? ie changed, stamp, ....

**Comment by valitsa** [comment]
- Record = indicator,  as currently stated in the database. 
- Column title in the dataview: Data entry date

**Comment by brtvrbvk** [comment]
ok, but you will need task will to change the scheme and add this data in the database

**Comment by valitsa** [comment]
ok, I assigned the task to Will

**Comment by willtemperley** [comment]
Do we want two fields, i.e. create_date and update_date? 
Just one which records either when the record was entered or updated?

**Comment by valitsa** [comment]
My suggestion is 

Database structure: two records
Data upload (the user interface): two records (to help users keep track of their activities)
Data view: Latest update only.

**Comment by willtemperley** [comment]
I assume you mean two columns. Anyway two columns, date_updated and date_created added which are managed by a trigger.  Both are populated when creation happens.
