### ISSUE TITLE
Establish clear links among the different classification schemes for ES

### ISSUE THREAD

**Issue by valitsa** [valitsa/ESPmapping#10]

**Comment by wieteke** [comment]
We had already figured out that the table Nev sent does not provide unique links. But now I am doubting of we actually need that clear link. The ES types are used to label ES map for searches, meaning that non-unique labels would to some false positive search results. Can we make a two-step approach: Uploaders indicate classification system and ES type ,and end-users should be allowed to search per classification system too. 
I would say we include CICES and TEEB. Did any of our ESP testers use/suggest MA?

**Comment by valitsa** [comment]
Joachim proposed the Bayesian network approach used by OpeNESS
http://openness.hugin.com/example/cices 
I think it's a good idea to start with

**Comment by wieteke** [comment]
Fancy!!
You already have a plan on how the probabilities (%) will lead to single
set of outcomes when applied to a search for ES maps in the tool?

Will we still stick to TEEB and CICES or are you planning to include more
classification systems now?

**Comment by valitsa** [comment]
It is quite fancy indeed. 
It is one of the "issues" that will be discussed tomorrow. 
Will let you know what was discussed.
