### ISSUE TITLE
Licencing agreement for data sharing. Can we use Creative Commons?? 

### ISSUE THREAD

**Issue by valitsa** [valitsa/ESPmapping#13]
I was checking a bit the website and found the type of license we might need (Attribution-NonCommercial-ShareAlike "CC BY-NC-SA"). http://creativecommons.org/licenses/by-nc-sa/3.0/

**Comment by willtemperley** [comment]
I'd say that's definitely an option. It's quite restrictive, therefore less likely to scare those that are afraid of e.g. commercial use of their work. However, I wonder if we could let a user choose how to license their work?  Give them  the option of all the CC licenses, plus for example the Open Database License: http://opendatacommons.org/licenses/odbl/

**Comment by valitsa** [comment]
My understanding was a bit different. Given that in most cases the maps etc will be part of scientific journal publication or another web application, I was mainly referring to adopting a CC license that will allow us to publish that data in our tool. 
Of course this depends on the licensing agreement they want to have. 
To reply to your comment, allowing each user to define their own type of licensing agreement is an option. Without any knowledge of what this might require technically and in terms of administrative arrangements, it sounds to me rather complex. If you think it's doable (in a reasonable amount of time), I want to know more.

**Comment by valitsa** [comment]
Update:
EC has a licence type for open data sharing similar to the CCBY one. 
Consultation with the EC Intellectual Property Rights people is ongoing.
