### ISSUE TITLE
Add base layers to the map viewer

### ISSUE THREAD

**Issue by valitsa** [valitsa/ESPmapping#2]
List of base layers:
- GLC2000
- Sea bathymetry layer

Other layers:
- Protected Areas (WDPA) (latest)
- White's Terrestrial Ecoregions (on hold)
- Marine Ecoregions Of the World (MEOW) (on hold) 
- Exclusive Economic Zones --> 
  \DAMON\gisdata\MONDE_GEODB\data\Administrative_Units\EEZ\World_EEZ_v7_2012_HR.shp 

For the 'Other' layers: only border no fill color

**Comment by valitsa** [comment]
Is there a possibility for the 'Other layers' to identify their name once you click on them?

**Comment by brtvrbvk** [comment]
This is possible.
need to know for each layer: 
- only name? Which field(s)
- when is identify active? (always, only when the layer is visible, when identify tool is activated, when layer is activated, combination of what is above,...)

**Comment by brtvrbvk** [comment]
I reopen this because the "identify" function is not finished yet
