### ISSUE TITLE
Develop the FAQ section

### ISSUE THREAD

**Issue by valitsa** [valitsa/ESPmapping#20]
Keep it short and simple. 
At this stage of the tool development it can comprise of really simple Q & As
Text will be provided by email. 

Do we want to enable a search function within the FAQ?
Does this mean we need another database for it?

**Comment by wieteke** [comment]
[Just testing if this commenting works]

I would group the FAQs instead of creating a search by eg "general", 'uploading maps", "searching maps" issues

**Comment by IgnaPa** [comment]
I agree with Wieteke. Have a look at InVEST FAQ from the Natural Capital Project:
http://www.naturalcapitalproject.org/FAQs.html

**Comment by valitsa** [comment]
I totally agree also. 
I found some documentation about how to structure and develop FAQs. Working on it still. I will send the doc for comments/edits etc.
