### ISSUE TITLE
Citation guide for the tool

### ISSUE THREAD

**Issue by valitsa** [valitsa/ESPmapping#21]
How does a user cite the tool? 
We need to produce relevant publication (Technical Guide?) either as a report or as a peer-reviewed.
e.g. Pert et al. 2013 (http://www.sciencedirect.com/science/article/pii/S016920461300039X)

**Comment by wieteke** [comment]
I would suggest a paper in our SI. Meanwhile we could use the technical guide as reference (or JRC report later, depending in time needed to get that out)

**Comment by valitsa** [comment]
Cool, I am working on the v5 of the Technical Guide and I will explore how much time the JRC report takes. 
100% in for the paper in our SI!
