### ISSUE TITLE
'Input Data Source' change of structure in the viewed blueprint

### ISSUE THREAD

**Issue by valitsa** [valitsa/ESPmapping#24]
The Input data source now is one column in the blueprint where users view info on the data source name and link if available. 
Make it two columns; one for the name and one for the link.

**Comment by brtvrbvk** [comment]
so, one datasource per map? Or multiple? (currently one, schema allows for multiple datasources)

**Comment by valitsa** [comment]
Multiple data sources per map

**Comment by willtemperley** [comment]
Duplicate of:
https://github.com/valitsa/ESPmapping/issues/23
