### ISSUE TITLE
When users download data a window shows up asking them to declare what they want to use it for

### ISSUE THREAD

**Issue by valitsa** [valitsa/ESPmapping#29]
It can be a pop-up window with some empty space where user can write down what they want to use the data for (e.g research, decision making). 
We can also have predefined list of options. 
That way we can identify our end-users.

**Comment by wieteke** [comment]
Like that. Can we also add a field at the tab where people score their uploaded map stating "is this ES map a direct input of a used decision support system?": Yes/No
To get an idea which maps are already used (without being downloaded from our tool).
