### ISSUE TITLE
List of biomes in the database

### ISSUE THREAD

**Issue by valitsa** [valitsa/ESPmapping#3]
Add new options in the biome table in the database

**Comment by willtemperley** [comment]
Suggest we use a recognised standard here, such as biomes from the ENVO ontology.

http://bioportal.bioontology.org/ontologies/ENVO/?p=classes&conceptid=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FENVO_00000428

**Comment by valitsa** [comment]
I agree, but we have to edit it especially in cases like the marine environment since the only classification they have there is "marine biome".

**Comment by willtemperley** [comment]
I think ENVO is in a state of flux at the moment, so perhaps worth engaging on the subject; suggesting marine biomes to be added or at least find out what they're up to.  It seems to be becoming a go-to point - e.g. TDWG are probably going to be using some ENVO terms in Darwin core soon.

http://sourceforge.net/mailarchive/message.php?msg_id=31446805

**Comment by valitsa** [comment]
I checked the ENVO ontology from the 2nd link you sent and the one I found is quite detailed, although different from the one we looked at last week.. 
I also found they now have a super detailed classification of the marine biomes! 
![marine_envo](https://f.cloud.github.com/assets/5603337/1341101/b0cbf652-3642-11e3-90d5-92d2374b1aae.png)

Is this subject to change? If yes, how do we add predefined fields in our database? How do we refer to it? 
If we can sort this out I find it quite detailed and I think we can definitely use it!

**Comment by valitsa** [comment]
I saw that there's also an ISBN number for the ontologies so citation is almost solved ;)

**Comment by willtemperley** [comment]
I got an excellent answer to this question:
http://answers.semanticweb.com/questions/22206/how-to-cite-an-ontological-concept-in-a-publication

So in short they suggest giving the following information: URI (ONTOLOGY, VERSION)
e.g. for the marine biome you would give: 
http://purl.obolibrary.org/obo/ENVO_00000447 (http://purl.bioontology.org/ontology/ENVO, releases/2013-06-14)

A little long winded perhaps but definitely unambiguous!

**Comment by valitsa** [comment]
EnvO was abandoned due to inconsistency within the classification. The TEEB one is being followed for now because:
a) It is ES relevant
b) It is agreed to be used also but the Marine ESP, with the plan to use it in order to make the two databases interoperable.
