### ISSUE TITLE
Only display maps that have been checked by trusted users

### ISSUE THREAD

**Issue by willtemperley** [valitsa/ESPmapping#35]
Will need a database field - e.g. "moderated" to indicate the map uploaded is publishable.

Presumably each time the map data themselves are changed, the content would need to be re-checked.

**Comment by valitsa** [comment]
I agree. 
Does this mean we need to have different types of user accounts? e.g. the ESP working group can be the administrators and those checking the quality of the uploaded data. 

If this is on, from our side we will have to set a set of standards that allows us to check the quality of the data.

**Comment by willtemperley** [comment]
I can create an "Administrator" group to which you'd all be added, which would give you access to a yet-to-be created administration area.  For example there could be a list of un-audited maps which would link to the map publisher, which would provide a functions for administrators to say "yep, publish".

**Comment by valitsa** [comment]
Great idea.
