### ISSUE TITLE
Predefined spatial entities, to which people can add attributes.

### ISSUE THREAD

**Issue by willtemperley** [valitsa/ESPmapping#36]
How often do people have maps with predefined entities and multiple attributes representing ES quantifications?

My suggestion would be to have some pre-defined entities, e.g. NUTS/countries/watersheds,  to which people could add their attributes, maybe by submitting an excel / CSV file or even manual editing.  These attributes would then be seen as an ES map.

This would mean:
1. Improved standardization of reporting units
2. There'd be much less data in the database
3. More easily comparable

**Comment by valitsa** [comment]
We need to discuss the pros and cons of this approach versus the old one and what kind of implications this might have for the users.
