### ISSUE TITLE
Input data source in the data upload

### ISSUE THREAD

**Issue by valitsa** [valitsa/ESPmapping#37]
On the data upload part, the multiple data sources per map are possible now. 
However, it means that we have to have a predefined list of data sources. 
This is not what we need. We want users to have the option to add info in two fields
a. data source (User names the data source, e.g. CORINE LC)
b. URL (User adds the corresponding URL)

Could it be something like what we have done with the Units? [Users add, but if it's already in the db it shows up?] In that case how do we allow them to select more than one? 
Given that the upload interface will change, will this also be changed?

**Comment by willtemperley** [comment]
It is what we need at the moment, we're just missing the ability to add data new sources.

**Comment by valitsa** [comment]
Yes, you're right. 
How will we allow people to add the data sources and the corresponding links?

**Comment by willtemperley** [comment]
Done
