### ISSUE TITLE
Link keywords and database info to improve search function

### ISSUE THREAD

**Issue by valitsa** [valitsa/ESPmapping#4]
Not sure how this can happen

**Comment by valitsa** [comment]
Example. A timber map does not come up when "forest" biome is filtered. 
Could this be improved if the biome field is made mandatory in the data upload?

**Comment by willtemperley** [comment]
Alternatively, if the biomes were linked to the ES (e.g. if timber provision was linked to the forest biome) then you could search for maps linked via the ES to the biome.

**Comment by valitsa** [comment]
To make sure I get it right, does this mean that withing the database the Biome info should be linked to the ES and not be an independent 'table'? If yes, I think it's a great idea. 
Questions: Will it be too much work for you? 
Do you have the time to do it?

**Comment by willtemperley** [comment]
It's not too much time - there'd just be a many to many link table - ecosystemservice2biome or something. Pretty easy from my side, more work for you I'd say, making the links!

**Comment by valitsa** [comment]
I see.
My idea was that the ES2biome link is not going to be pre-defined. 
In cases like timber and forest it might seem easy, but when we talk about entries like 'carbon sequestration' it can be marine or terrestrial biomes or both. 
Can we allow the users to define that relationship during the data upload? 
How much does this complicate things in terms of db structure?

**Comment by willtemperley** [comment]
I think that just comes right back to where we are now - the user links a Biome to an ES Indicator.  The user linking a Biome to a ES doesn't really make sense unless it has some context (i.e. the indicator)

The point of pre-defining the links was it doesn't require action on the part of the user.
