### ISSUE TITLE
Create a single administrative units table

### ISSUE THREAD

**Issue by willtemperley** [valitsa/ESPmapping#40]
This would contain _all_  relevant administrative units: EEZs, Countries, Regions ... etc

Users would then have the option to tag an ES indicator/map with any combination of the above.  A filter on administrative unit type would be provided.

**Comment by wieteke** [comment]
Optional sounds good (or we add extra options "within", "complete"?)
Many studies map ES for areas with natural/non or cross-admin boundaries; biomes, watersheds, landscapes,
