### ISSUE TITLE
See file size when a map is being downloaded

### ISSUE THREAD

**Issue by valitsa** [valitsa/ESPmapping#6]

**Comment by willtemperley** [comment]
This is tricky; The geoserver download isn't the same as the original data - it's been reprojected to WGS84 and I don't know if the bit depth is preserved.  This is probably a limitation in itself.

**Comment by valitsa** [comment]
Yes, but the users will be downloading the data from the geoserver anyway. 
So they will just have to know the size of the file they download. That's all I meant.

To reply to you, for this we can have a message telling them that this is not the original file and if they want to have access to that, they will have to contact the corresponding person.
