### ISSUE TITLE
Create a fabulous publisher for maps, like CartoDB.

### ISSUE THREAD

**Issue by willtemperley** [valitsa/ESPmapping#7]
How about doing things the other way round - i.e. the user creates a map, styles it, then adds all the metadata in a step by step fashion.

**Comment by valitsa** [comment]
Cool!

**Comment by valitsa** [comment]
Will, can you make an example of this idea that we can have a look at?

**Comment by willtemperley** [comment]
Take a look at CartoDB:
https://cartodb.com/signup

**Comment by valitsa** [comment]
Yes, I remember that. Looks cool. 
Are we going to try this?

**Comment by willtemperley** [comment]
My idea is to make the map publishing the first thing people do.  Then they get to see a pretty published map online. (perhaps they could even embed it in their own sites, rather like CartoDB, which would be an incentive to publish on the site).  Then, the user would enter the metadata - perhaps we could make it so that it only gets made publically visible after a certain amount of metadata has been entered - again incentivising data entry.

Linked issues:
https://github.com/valitsa/ESPmapping/issues/35

**Comment by valitsa** [comment]
I think that's a good idea cause it's more direct and user sees the result immediately. 
Like you said we have to make sure that they will be uploading most of the metadata by making fields mandatory.

How much time and effort does this require from you? Is it a complete restructuring? Do you have time for that?

**Comment by willtemperley** [comment]
It's not a lot of work to just switch the workflow around - I can reuse most of the components anyway. This would take a day or two, excluding the map publishing component.  Actually it simplifies some things - the workflow was getting very tricky with publishing the map right at the end.

Most of the work will be with the component for map publishing (colour maps etc) - something that needs doing anyway.  Still, worth doing I think and almost certainly useful across multiple projects.  Something basic could take a day or two, something like cartodb a few months ...

**Comment by valitsa** [comment]
Great! 
Let's do it then and let's discuss the differences between the 'basic' and 'cartodb' version.
