### ISSUE TITLE
Add explanation to filter criteria

### ISSUE THREAD

**Issue by valitsa** [valitsa/ESPmapping#8]
Add an i button next to each filter which will provide a written explanation of what the filter is about as well as definitions on the selection fields.

**Comment by brtvrbvk** [comment]
- what text should shown exactly?
- as a tooltip, a mesagebox, ....
- what do you mean by definitions?

**Comment by valitsa** [comment]
Next to each Filter name (Ecosystem Services, Biomes, etc) add an info symbol. 
![images](https://f.cloud.github.com/assets/5603337/1295791/e988340e-30b8-11e3-839f-64b83b712b22.jpg)
Once the user clicks on it a tooltip pops up with a short descriptive text per filter:
1. Ecosystem Services: 
"Select the Ecosystem Services you want to search for in the database. Classification is according to the TEEB (2010)." (hyperlink for TEEB: http://www.teebweb.org/publication/the-economics-of-ecosystems-and-biodiversity-teeb-ecological-and-economic-foundations/#.UlUWYBAeq0Y)
2. Biomes: (to do once we agree on the content)
3. Spatial Scale: (is there an ontology on that? )
4. Study Purpose: "Search the database according to the rationale of the study. Definitions provided in Egoh et al. 2011." (hyperlink for Egoh et al.: http://bookshop.europa.eu/en/indicators-for-mapping-ecosystem-services-pbLBNA25456/;pgid=y8dIS7GUWMdSR0EAlMEUUsWb0000bkrukNw9;sid=WLtBrKQaKC9BsPRgnh_fC8Y_-ng9_Ol5Rsk=?CatalogCategoryID=7QwKABstDHwAAAEjK5EY4e5L)

**Comment by brtvrbvk** [comment]
+- done, waiting for text on biomes and eventually spatialscale

**Comment by valitsa** [comment]
I will send them, once we finalise the content
